"""test_superuser

Revision ID: ceed7fde818e
Revises: 54c3c0b91fc9
Create Date: 2024-02-23 11:47:45.391265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceed7fde818e'
down_revision = '54c3c0b91fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
